### PR TITLE
After many hours

### PR DESCRIPTION
**Pull request by GulcanGuvenCalan**

### CODE REVIEW

**Review by VedatDaglar — APPROVED** [review]

**Comment by VedatDaglar** [comment]
Gülcan  i did Human Resources scenarios just with "Human Resources" parameters 
like this one. But you can decide which one you use. But maybe less code if we use like that. Anyway it's just my opinion. 
Screenshot 2022-11-13 at 02 41 16

**Comment by VedatDaglar** [comment]
👍

**Comment by VedatDaglar** [comment]
Gülcan i tried to run after i merged your pull&request. Your first three scenarios are passing but the last one is failed. Tomorrow can you fix it and merge again please. I understand you i also spent long hours to do this task. So maybe you can try to fix it first and maybe you can also compare with mazher's previous sprint feeature file. 👍 

https://github.com/VedatDaglar/Mz_Project.git


Screenshot 2022-11-13 at 02 50 47

Screenshot 2022-11-13 at 02 50 34

**Review by VedatDaglar — APPROVED** [review]

**Comment by VedatDaglar** [comment]
All test are passing now 👍

**Comment by GulcanGuvenCalan** [comment]
Thank you for your email I will do

**Pull request merged**
